# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'Knockt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Knockt
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for Google signin
  pod 'Google/SignIn'

  # Pods for HTTP
  pod 'Alamofire', '~> 4.0'
end

